export const defaultCategoriesSeed = {
    INCOME: [
        {
            name: "Salary",
            group: "Income",
            icon: "Wallet",
            color: "#22C55E",
        },
        {
            name: "Bonus",
            group: "Income",
            icon: "BadgeDollarSign",
            color: "#16A34A",
        },
        {
            name: "Freelance",
            group: "Income",
            icon: "Laptop",
            color: "#0EA5E9",
        },
        {
            name: "Business",
            group: "Income",
            icon: "BriefcaseBusiness",
            color: "#2563EB",
        },
        {
            name: "Investment",
            group: "Income",
            icon: "TrendingUp",
            color: "#10B981",
        },
        {
            name: "Dividend",
            group: "Income",
            icon: "ChartCandlestick",
            color: "#059669",
        },
        {
            name: "Interest",
            group: "Income",
            icon: "Percent",
            color: "#84CC16",
        },
        {
            name: "Rental Income",
            group: "Income",
            icon: "Building2",
            color: "#65A30D",
        },
        {
            name: "Cashback",
            group: "Income",
            icon: "BadgePercent",
            color: "#14B8A6",
        },
        {
            name: "Refund",
            group: "Income",
            icon: "RotateCcw",
            color: "#06B6D4",
        },
        {
            name: "Gift",
            group: "Income",
            icon: "Gift",
            color: "#EC4899",
        },
        {
            name: "Scholarship",
            group: "Income",
            icon: "GraduationCap",
            color: "#6366F1",
        },
        {
            name: "Pension",
            group: "Income",
            icon: "Landmark",
            color: "#8B5CF6",
        },
        {
            name: "Lottery",
            group: "Income",
            icon: "Ticket",
            color: "#F59E0B",
        },
        {
            name: "Other Income",
            group: "Income",
            icon: "CircleDollarSign",
            color: "#64748B",
        },
    ],

    EXPENSE: [
        {
            name: "Food",
            group: "Food & Drinks",
            icon: "UtensilsCrossed",
            color: "#F97316",
        },
        {
            name: "Grocery",
            group: "Food & Drinks",
            icon: "ShoppingBasket",
            color: "#22C55E",
        },
        {
            name: "Restaurant",
            group: "Food & Drinks",
            icon: "ChefHat",
            color: "#EF4444",
        },
        {
            name: "Coffee",
            group: "Food & Drinks",
            icon: "Coffee",
            color: "#92400E",
        },
        {
            name: "Fast Food",
            group: "Food & Drinks",
            icon: "Pizza",
            color: "#DC2626",
        },
        {
            name: "Fuel",
            group: "Transportation",
            icon: "Fuel",
            color: "#F59E0B",
        },
        {
            name: "Car",
            group: "Transportation",
            icon: "Car",
            color: "#2563EB",
        },
        {
            name: "Bike",
            group: "Transportation",
            icon: "Bike",
            color: "#06B6D4",
        },
        {
            name: "Bus",
            group: "Transportation",
            icon: "Bus",
            color: "#4F46E5",
        },
        {
            name: "Train",
            group: "Transportation",
            icon: "Train",
            color: "#7C3AED",
        },
        {
            name: "Flight",
            group: "Travel",
            icon: "Plane",
            color: "#0EA5E9",
        },
        {
            name: "Shopping",
            group: "Shopping",
            icon: "ShoppingCart",
            color: "#EC4899",
        },
        {
            name: "Clothes",
            group: "Shopping",
            icon: "Shirt",
            color: "#DB2777",
        },
        {
            name: "Electronics",
            group: "Shopping",
            icon: "Laptop",
            color: "#3B82F6",
        },
        {
            name: "Rent",
            group: "Home",
            icon: "House",
            color: "#8B5CF6",
        },
        {
            name: "Electricity",
            group: "Bills & Utilities",
            icon: "Zap",
            color: "#EAB308",
        },
        {
            name: "Water Bill",
            group: "Bills & Utilities",
            icon: "Droplets",
            color: "#06B6D4",
        },
        {
            name: "Gas Bill",
            group: "Bills & Utilities",
            icon: "Flame",
            color: "#EA580C",
        },
        {
            name: "Internet",
            group: "Bills & Utilities",
            icon: "Wifi",
            color: "#0284C7",
        },
        {
            name: "Mobile Recharge",
            group: "Bills & Utilities",
            icon: "Smartphone",
            color: "#4F46E5",
        },
        {
            name: "Health",
            group: "Health",
            icon: "HeartPulse",
            color: "#DC2626",
        },
        {
            name: "Medicine",
            group: "Health",
            icon: "Pill",
            color: "#EF4444",
        },
        {
            name: "Doctor",
            group: "Health",
            icon: "Stethoscope",
            color: "#2563EB",
        },
        {
            name: "Education",
            group: "Education",
            icon: "GraduationCap",
            color: "#6366F1",
        },
        {
            name: "Books",
            group: "Education",
            icon: "BookOpen",
            color: "#7C3AED",
        },
        {
            name: "Movies",
            group: "Entertainment",
            icon: "Film",
            color: "#F43F5E",
        },
        {
            name: "Music",
            group: "Entertainment",
            icon: "Music",
            color: "#A855F7",
        },
        {
            name: "Games",
            group: "Entertainment",
            icon: "Gamepad2",
            color: "#8B5CF6",
        },
        {
            name: "EMI",
            group: "Finance",
            icon: "ReceiptIndianRupee",
            color: "#EA580C",
        },
        {
            name: "Insurance",
            group: "Finance",
            icon: "ShieldCheck",
            color: "#0F766E",
        },
        {
            name: "Tax",
            group: "Finance",
            icon: "Receipt",
            color: "#64748B",
        },
        {
            name: "Charity",
            group: "Personal",
            icon: "HeartHandshake",
            color: "#E11D48",
        },
        {
            name: "Pet",
            group: "Personal",
            icon: "Dog",
            color: "#92400E",
        },
        {
            name: "Office",
            group: "Others",
            icon: "Briefcase",
            color: "#475569",
        },
        {
            name: "Other Expense",
            group: "Others",
            icon: "CircleEllipsis",
            color: "#64748B",
        },
    ],
} as const;